import img1 from '../Main-page/image/img1.webp'
import img2 from '../Main-page/image/img2.webp'
import img3 from '../Main-page/image/img3.webp'
import img4 from '../Main-page/image/img4.webp'
let Scarddata =[

    
    {
        id:1,
        image: img1,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/510gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/510gm',
        option4:'Cruncy/1kg',
              
        
    },  
    {
        id:2,
        image:img2 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Creamy/350gm',
        option2:'Creamy/1kg',
        option3:'Creamy/2.5kg',
        option4:'Cruncy/350gm',
        option5:'Cruncy/1kg', 
        option6:'Cruncy/2.5kg',
        option7:' Extra cruncy/350gm',
        option8:'Extra cruncy/1kg',
        
    },
    {
        id:3,
        image:img3 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/350gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/2.5kg',
        option4:'Creamy/350gm',
        option5:'Creamy/1kg', 
        option6:'Creamy/2.5kg',
       
              
    },
    {
        id:4,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:5,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:6,
        image: img1,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/510gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/510gm',
        option4:'Cruncy/1kg',
              
        
    },  
    {
        id:7,
        image:img2 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Creamy/350gm',
        option2:'Creamy/1kg',
        option3:'Creamy/2.5kg',
        option4:'Cruncy/350gm',
        option5:'Cruncy/1kg', 
        option6:'Cruncy/2.5kg',
        option7:' Extra cruncy/350gm',
        option8:'Extra cruncy/1kg',
        
    },
    {
        id:8,
        image:img3 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/350gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/2.5kg',
        option4:'Creamy/350gm',
        option5:'Creamy/1kg', 
        option6:'Creamy/2.5kg',
       
              
    },
    {
        id:9,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:10,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:11,
        image: img1,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/510gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/510gm',
        option4:'Cruncy/1kg',
              
        
    },  
    {
        id:12,
        image:img2 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Creamy/350gm',
        option2:'Creamy/1kg',
        option3:'Creamy/2.5kg',
        option4:'Cruncy/350gm',
        option5:'Cruncy/1kg', 
        option6:'Cruncy/2.5kg',
        option7:' Extra cruncy/350gm',
        option8:'Extra cruncy/1kg',
        
    },
    {
        id:13,
        image:img3 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/350gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/2.5kg',
        option4:'Creamy/350gm',
        option5:'Creamy/1kg', 
        option6:'Creamy/2.5kg',
       
              
    },
    {
        id:14,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:15,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:16,
        image: img1,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/510gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/510gm',
        option4:'Cruncy/1kg',
              
        
    },  
    {
        id:17,
        image:img2 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Creamy/350gm',
        option2:'Creamy/1kg',
        option3:'Creamy/2.5kg',
        option4:'Cruncy/350gm',
        option5:'Cruncy/1kg', 
        option6:'Cruncy/2.5kg',
        option7:' Extra cruncy/350gm',
        option8:'Extra cruncy/1kg',
        
    },
    {
        id:18,
        image:img3 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/350gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/2.5kg',
        option4:'Creamy/350gm',
        option5:'Creamy/1kg', 
        option6:'Creamy/2.5kg',
       
              
    },
    {
        id:19,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:20,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    }, {
        id:21,
        image: img1,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/510gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/510gm',
        option4:'Cruncy/1kg',
              
        
    },  
    {
        id:22,
        image:img2 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Creamy/350gm',
        option2:'Creamy/1kg',
        option3:'Creamy/2.5kg',
        option4:'Cruncy/350gm',
        option5:'Cruncy/1kg', 
        option6:'Cruncy/2.5kg',
        option7:' Extra cruncy/350gm',
        option8:'Extra cruncy/1kg',
        
    },
    {
        id:23,
        image:img3 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/350gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/2.5kg',
        option4:'Creamy/350gm',
        option5:'Creamy/1kg', 
        option6:'Creamy/2.5kg',
       
              
    },
    {
        id:24,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:25,
        image: img4 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Unsalted',
        option2:'Salted',
        option3:'Multigrain',
        option4:'Multigrain Salted',
              
    },
    {
        id:26,
        image: img1,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/510gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/510gm',
        option4:'Cruncy/1kg',
              
        
    },  
    {
        id:27,
        image:img2 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Creamy/350gm',
        option2:'Creamy/1kg',
        option3:'Creamy/2.5kg',
        option4:'Cruncy/350gm',
        option5:'Cruncy/1kg', 
        option6:'Cruncy/2.5kg',
        option7:' Extra cruncy/350gm',
        option8:'Extra cruncy/1kg',
        
    },
    {
        id:28,
        image:img3 ,
        titless : 'High Protein Dark Chocolate Peanut Butter',
        fromes :'from',
        rss:'RS.379',
        opp :'RS.399',
        option1:'Cruncy/350gm',
        option2:'Cruncy/1kg',
        option3:'Cruncy/2.5kg',
        option4:'Creamy/350gm',
        option5:'Creamy/1kg', 
        option6:'Creamy/2.5kg',
       
              
    }
  
]

export default Scarddata;
